### ISSUE TITLE
KibanaIsServerless check causes 400 Bad Request errors on Stateful Kibana

### ISSUE THREAD

**Issue by strawgate** [elastic/elastic-agent-libs#181]
Our new KibanaIsServerless check causes hard to track down noise in the Kibana log in stateful environments.

From discuss: https://discuss.elastic.co/t/elasticsearch-output-of-filebeat-is-empty-displays-http-error-400-bad-request/352407

https://github.com/elastic/elastic-agent-libs/blob/473983911d7c78e57bf30af91f66f5bca50d0a59/kibana/client.go#L351-L359
```
GET kbn:/api/saved_objects/_find
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "[request query.type]: expected at least one defined value but got [undefined]"
}
```

![image](https://github.com/elastic/elastic-agent-libs/assets/6384545/341d2ec1-3051-45c4-80ff-f613986364ed)

**Comment by cmacknz** [comment]
@fearful-symmetry I think at the time we wrote this there wasn't a better way to tell if we were connected to serverless Kibana, so instead we used an API that didn't exist in stateful, correct?

Were there ever plans to implement an API for this detection? Or is that something we need to follow up on?

**Comment by strawgate** [comment]
My uneducated guess is this call returns:
"method [get] exists but is not available with the current configuration" with a 400 error on serverless

Fixing it on stateful may just require giving it the required query parameter like: `kbn:/api/saved_objects/_find?type=index-pattern`

Ideally a dedicated API would be better but adding the type would be a quick fix here

**Comment by fearful-symmetry** [comment]
@cmacknz yah, at the time that code was written, we didn't really have a good way to detect serverless mode in Kibana. It's totally a hack (I even called it a hack [in the commit](https://github.com/elastic/elastic-agent-libs/pull/150/commits/e831be1dd2d1a3552a7f51e585479152dc9efc1f)). However, that was a long time ago, and hopefully the API has changed. I can ask the slack channel.

**Comment by afharo** [comment]
Hey! I just found out this behavior and was about to report it. Glad that you had it on your radar. 

Just letting you know that `GET /api/status` already reports the `version.build_flavor: "traditional" | "serverless"`.

You can rely on that now.

**Comment by lukeelmers** [comment]
@cmacknz @strawgate @fearful-symmetry `/api/saved_objects/_find` has been deprecated for awhile now and @elastic/kibana-core is proposing removing it in 9.0. So at this point you should migrate to using the `build_flavor` from `/api/status` as mentioned in the link above. This is the "official" way of determining whether you are talking to serverless Kibana. As long as you are authenticated, you should get `version.build_flavor` back in the response. (Unauthenticated requests to `/api/status` will not include this info).

**Comment by fearful-symmetry** [comment]
@pierrehilbert we should put this on the board for the next 1-2 sprints or something; this is probably an easy fix
